# Generated by Django 5.1.2 on 2024-10-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Аксесуар', models.CharField(max_length=100)),
                ('Цена', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Аксесуар',
                'verbose_name_plural': 'Аксесуары',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Цена', models.IntegerField()),
                ('Товар', models.CharField(max_length=100)),
                ('Тип', models.CharField(max_length=100)),
                ('Модель', models.CharField(max_length=100)),
                ('Оперативная память', models.CharField(max_length=100)),
                ('Память', models.CharField(max_length=100)),
                ('DataRelise', models.DateField()),
                ('Разрешение телефона', models.CharField(max_length=100)),
                ('keyProduct', models.IntegerField()),
                ('Гарантия', models.CharField(max_length=100)),
                ('Фото', models.ImageField(upload_to='./MainWeb/static/img')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
